### PR TITLE
fix badge and ci.

### PR DESCRIPTION
**Pull request by asm256**
old ruby => old gem.
latest ruby => latest gem.

rbx ... sorry , i dont know.

### CODE REVIEW

**Comment by ConradIrwin** [comment]
Thanks @asm256 — Happy to merge this, but I'm confused by the need for the public_suffix/mime-types gems. What are they required for?

**Comment by asm256** [comment]
@ConradIrwin Thanks comment.

public_suffix/mime-types both are required from capybara.
But, [capybara](https://rubygems.org/gems/capybara) is requesting a newer version indefinitely.

**Comment by ConradIrwin** [comment]
Awesome! Thanks for finally making CI green :D.

**Comment by ConradIrwin** [comment]
P.S. I've added you as a contributor to this repo. Please feel free to make yourself at home, and send more PRs/review other people's.

Thanks again :)

**Pull request merged**
